version: '3.7'

services:
        list-server:
                build:
                        context: .docker-compose/server/
                image: local-list-server-image
                volumes:
                        - .:/app
                working_dir: /app
                hostname: server.listdev
                domainname: listdev
                ports:
                        - 80:80
                extra_hosts:
                        - "server.listdev:127.0.0.1"
                links:
                        - list-database
                environment:
                        LIST_DATABASE_HOSTNAME: list-database
                        LIST_DATABASE_USER: root
                        LIST_DATABASE_PASSWORD: root
                        LIST_DATABASE_NAME: list-dev
                        LIST_CONFIG_BASE_URL: http://server.listdev/

        list-database:
                image: mariadb:10
                environment:
                        MYSQL_ROOT_PASSWORD: root
                        MYSQL_DATABASE: list-dev
                volumes:
                        - list-database-data:/var/lib/mysql

        list-adminer:
                image: adminer:latest
                links:
                        - list-database
                hostname: server.listdev
                domainname: listdev
                ports:
                        - 8080:8080
                extra_hosts:
                        - "server.listdev:127.0.0.1"
                environment:
                        ADMINER_DEFAULT_SERVER: list-database

volumes:
        list-database-data:

