version: '3.7'

services:
  list-server:
    build:
      context: .docker-compose/server/
    image: local-list-server-image
    volumes:
      - .:/app
    working_dir: /app
    hostname: server.listdev
    domainname: listdev
    ports:
      - 80:80
    extra_hosts:
      - "server.listdev:127.0.0.1"
    links:
      - list-database
      - list-rabbitmq
    environment:
      LIST_DATABASE_HOSTNAME: list-database
      LIST_DATABASE_USER: root
      LIST_DATABASE_PASSWORD: root
      LIST_DATABASE_NAME: list-dev
      LIST_CONFIG_BASE_URL: http://server.listdev/
      LIST_ENVIRONMENT: development
      LIST_AMQP_HOST: list-rabbitmq
      LIST_AMQP_PORT: 5672
      LIST_AMQP_USER: guest
      LIST_AMQP_PASSWORD: guest
      LIST_AMQP_VHOST: list
      XDEBUG_CONFIG: >
        remote_host=host.docker.internal
        remote_autostart=1
        remote_connect_back=0

  list-database:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: list-dev
    volumes:
      - list-database-data:/var/lib/mysql
    ports:
      - 43306:3306
    hostname: server.listdev
    domainname: listdev

  list-adminer:
    image: adminer:latest
    links:
      - list-database
    hostname: server.listdev
    domainname: listdev
    ports:
      - 8080:8080
    extra_hosts:
      - "server.listdev:127.0.0.1"
    environment:
      ADMINER_DEFAULT_SERVER: list-database

  list-rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: server.listdev
    domainname: listdev
    ports:
      - 15672:15672
      - 15692:15692
    extra_hosts:
      - "server.listdev:127.0.0.1"

volumes:
  list-database-data:

